# Generated by Django 5.2.6 on 2025-09-21 17:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the project",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the project"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PL", "Planned"),
                            ("IP", "In Progress"),
                            ("OH", "On Hold"),
                            ("CO", "Completed"),
                            ("AR", "Archived"),
                        ],
                        default="PL",
                        help_text="Current status of the project",
                        max_length=2,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MED", "Medium"),
                            ("HI", "High"),
                            ("CRIT", "Critical"),
                        ],
                        default="MED",
                        help_text="Priority level of the project",
                        max_length=4,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Planned or actual start date of the project",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Planned or actual end date of the project",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Team members working on this project",
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the label",
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#808080",
                        help_text="Hex color code for the label (e.g., #FF0000 for red)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this label belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Label",
                "verbose_name_plural": "Project Labels",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="project_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["priority"], name="project_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_by"], name="project_created_by_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("name", "created_by"),
                name="unique_project_name_per_creator",
                violation_error_message="You already have a project with this name.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_date__isnull", True), ("start_date__isnull", True)),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="end_date_after_start_date",
                violation_error_message="End date must be after start date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectlabel",
            constraint=models.UniqueConstraint(
                fields=("name", "project"),
                name="unique_label_name_per_project",
                violation_error_message="A label with this name already exists in this project.",
            ),
        ),
    ]
